name: Auto Marking

on:
  push:
    branches:
      - '**'

jobs:
  run-marking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install Backend Dependencies
        run: |
          npm install

      - name: Start NestJS Backend
        run: |
          npm run start & npm run start:basic-processing
        shell: bash

      - name: Wait for Backend to Be Ready
        run: |
          echo "Waiting for backend to start..."
          for i in {1..30}; do
            if curl --fail http://localhost:3000; then
              echo "Backend is ready!"
              break
            fi
            sleep 2
          done

      - name: Call API for Auth (or other keys)
        run: |
          curl -X POST http://localhost:3000/basic-processing/negative \
            -H "Content-Type: application/json" \
            -d '{"imagePath": "apps/cse40/images/input_image.png"}'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow numpy

      - name: Run Marking Script
        run: |
          python test/run_marking.py
