name: Auto Marking

on:
  push:
    branches:
      - '**'

jobs:
  run-marking:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          npm install
          npm install concurrently
          python -m pip install --upgrade pip
          pip install pillow numpy httpx

      - name: Start Services, Check APIs, and Run Tests
        run: |
          # Start NestJS services in the background
          npx concurrently "npm run start" "npm run start:basic-processing" &

          # Wait for the ports to open
          echo "Waiting for services to start..."
          for i in {1..30}; do
            nc -z localhost 3000 && nc -z localhost 4001 && break
            echo "Waiting for ports 3000 and 4001..."
            sleep 1
          done

          curl --fail -X POST http://localhost:3000/basic-processing/greyscale \
            -H "Content-Type: application/json" \
            -d '{"imagePath": "apps/cse40/images/input_image.png"}' || exit 1

          echo "✅ APIs are reachable and responding to requests"

          # Run Python test scripts
          for file in test/single_tests/test_*.py; do
            echo "Running $file"
            python "$file"
          done